[[redirects]]
  from = "/:year(\\d{4})/:month(\\d{2})/:day(\\d{2})/*"
  to = "/post/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/join-the-cso-ffd-group"
  to = "/the-mechanism"

[[redirects]]
  from = "/ffd-forum-2"
  to = "/ffd-forum"

[[redirects]]
  from = "/ffd-forum-2024"
  to = "/conference/ffd-forum"

[[redirects]]
  from = "/collective-contribution-ffd-forum-2024"
  to = "/conference/ffd-forum"

[[redirects]]
  from = "/ffd-forum-2023"
  to = "/conference/past-forums/past-forums/forum-2023"

[[redirects]]
  from = "/collective-contribution-ffd-forum-2023"
  to = "/conference/past-forums/past-forums/forum-2023"
  
[[redirects]]
  from = "/ffd-forum-2022"
  to = "/conference/past-forums/past-forums/forum-2022"

[[redirects]]
  from = "/collective-contribution-ffd-forum-2022"
  to = "/conference/past-forums/past-forums/forum-2022"

[[redirects]]
  from = "/ffd-forum-2021"
  to = "/conference/past-forums/past-forums/ffd-forum-2021"

[[redirects]]
  from = "/collective-contribution-ffd-forum-2021"
  to = "/conference/past-forums/past-forums/forum-2021"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2020"
  to = "/conference/past-forums/past-forums/ffd-forum-2020"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2020/cso-collective-contribution-ffd-forum-2020"
  to = "/conference/past-forums/past-forums/forum-2020"

[[redirects]]
  from = "/ffd-forum-2/forum-2019"
  to = "/conference/past-forums/past-forums/ffd-forum-2019"

[[redirects]]
  from = "/ffd-forum-2/forum-2019/cso-collective-contribution-ffd-forum-2019"
  to = "/conference/past-forums/past-forums/ffd-forum-2020"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2018"
  to = "/conference/past-forums/past-forums/ffd-forum-2018"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2018/cso-participation-ffd-forum-2018"
  to = "/conference/past-forums/past-forums/ffd-forum-2018"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2018/cso-side-events-ffd-forum-2018"
  to = "/conference/past-forums/past-forums/ffd-forum-2018"

[[redirects]]
  from = "/ffd-forum-2/ffd-forum-2018/cso-collective-contribution-ffd-forum-2018"
  to = "/conference/past-forums/past-forums/ffd-forum-2018/"

[[redirects]]
  from = "/ffd-forum"
  to = "/conference/past-forums/past-forums/ffd-forum-2017"

[[redirects]]
  from = "/ffd-follow-up-forum"
  to = "/conference/past-forums/past-forums/ffd-forum-2016"

[[redirects]]
  from = "/third-ffd-conference"
  to = "/conference/past-conferences-3rd-ffd-conference"

[[redirects]]
  from = "/third-ffd-conference"
  to = "/conference/past-conferences-3rd-ffd-conference"

[[redirects]]
  from = "/global-economic-solutions-now"
  to = "/resources"

[[redirects]]
  from = "/economic-reconstruction-and-systemic-reforms-summit-at-the-un"
  to = "/resources"

[[redirects]]
  from = "/statements"
  to = "/resources"

[[redirects]]
  from = "/op-eds-articles"
  to = "/resources"

[[redirects]]
  from = "/infographics-videos"
  to = "/resources"

[[redirects]]
  from = "/campaign-updates"
  to = "/resources"

[[redirects]]
  from = "/covid19-ffd-resources-2"
  to = "/resources"

[[redirects]]
  from = "/general-resources"
  to = "/resources"

[[redirects]]
  from = "/gender"
  to = "/areas-of-work"

[[redirects]]
  from = "/debt"
  to = "/work/debt/"

[[redirects]]
  from = "/drm-tax"
  to = "/work/tax"

[[redirects]]
  from = "/international-development-cooperation"
  to = "/work/idc"

[[redirects]]
  from = "/private-finance"
  to = "/work/private-finance"

[[redirects]]
  from = "/systemic-issues-financial-regulation"
  to = "work/systemic-issues"

[[redirects]]
  from = "/2023/07/13/the-complete-toolkit-an-introductory-guide-to-ffd"
  to = "/post/the-complete-toolkit-an-introductory-guide-to-ffd"